/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import Backend.DrawingEngine;
import Backend.Shape;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author eyada
 */
public class PaintScreen extends javax.swing.JPanel implements DrawingEngine{

    ArrayList<Shape> shapes = new ArrayList<>();
    int counter=0;
    /**
     * Creates new form DrawingArea
     */
    public PaintScreen(){
       initComponents();
   }
           
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        for(Shape s: shapes){
            s.draw(g);
        }
    }
    @Override
    public void addShape(Shape shape) {
        shapes.add(shape);
    }

    @Override
    public void removeShape(Shape shape) {
        for(int i=0;i<shapes.size();i++)
        {
            if(shapes.get(i).equals(shape))
                shapes.remove(shapes.get(i));
        }
    }

    @Override
    public Shape[] getShapes() {
        Shape[] shapesArr = new Shape[shapes.size()];
        return shapes.toArray(shapesArr);
    }

    @Override
    public void refresh(Graphics canvas) {
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
