/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import Backend.*;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author eyada
 */
public class Painter extends javax.swing.JFrame {

    /**
     * Creates new form Painter
     */
    public Painter() {
        super("Painter");
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rectanglelabel = new javax.swing.JLabel();
        circleButton = new javax.swing.JButton();
        squareButton = new javax.swing.JButton();
        rectangleButton = new javax.swing.JButton();
        linesegmentButton = new javax.swing.JButton();
        squarelabel = new javax.swing.JLabel();
        linesegmentlabel = new javax.swing.JLabel();
        circlelabel = new javax.swing.JLabel();
        ChooseShape = new javax.swing.JComboBox<>();
        selectshapelabel = new javax.swing.JLabel();
        colorizebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        paintScreen1 = new frontend.PaintScreen();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rectanglelabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        rectanglelabel.setForeground(new java.awt.Color(204, 204, 0));
        rectanglelabel.setText("Rectangle");
        jPanel1.add(rectanglelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 60, 20));

        circleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/circle.jpeg"))); // NOI18N
        circleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(circleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 30, 30));

        squareButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/square.png"))); // NOI18N
        squareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareButtonActionPerformed(evt);
            }
        });
        jPanel1.add(squareButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 20, 30, -1));

        rectangleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/rectangle.jpeg"))); // NOI18N
        rectangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rectangleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 20, 50, 30));

        linesegmentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/line segment.jpeg"))); // NOI18N
        linesegmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linesegmentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(linesegmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 50, 30));

        squarelabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        squarelabel.setForeground(new java.awt.Color(204, 204, 0));
        squarelabel.setText("Square");
        jPanel1.add(squarelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        linesegmentlabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        linesegmentlabel.setForeground(new java.awt.Color(204, 204, 0));
        linesegmentlabel.setText("Line segment");
        jPanel1.add(linesegmentlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        circlelabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        circlelabel.setForeground(new java.awt.Color(204, 204, 0));
        circlelabel.setText("Circle");
        jPanel1.add(circlelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        ChooseShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose shape" }));
        jPanel1.add(ChooseShape, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));

        selectshapelabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        selectshapelabel.setForeground(new java.awt.Color(204, 204, 0));
        selectshapelabel.setText("Select shape");
        jPanel1.add(selectshapelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 107, 100, 30));

        colorizebutton.setText("Colorize");
        colorizebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorizebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(colorizebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        paintScreen1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout paintScreen1Layout = new javax.swing.GroupLayout(paintScreen1);
        paintScreen1.setLayout(paintScreen1Layout);
        paintScreen1Layout.setHorizontalGroup(
            paintScreen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        paintScreen1Layout.setVerticalGroup(
            paintScreen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanel1.add(paintScreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 580, 490));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/backgorund.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 790, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void circleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleButtonActionPerformed
        Point p =new Point();
        p.x=Integer.parseInt(JOptionPane.showInputDialog("Enter x-coordintes of the circle  :"));
        p.y=Integer.parseInt(JOptionPane.showInputDialog("Enter y-coordintes of the circle  :"));
        int r = Integer.parseInt(JOptionPane.showInputDialog("Enter radius :"));
        Circle c=new Circle(p, Color.darkGray, Color.yellow, r);
        paintScreen1.addShape(c);
        paintScreen1.repaint();
        paintScreen1.counter++;
        ChooseShape.addItem("Circle " + paintScreen1.counter);
    }//GEN-LAST:event_circleButtonActionPerformed

    private void squareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareButtonActionPerformed
        Point p =new Point();
        p.x=Integer.parseInt(JOptionPane.showInputDialog("Enter x-coordintes of the square  :"));
        p.y=Integer.parseInt(JOptionPane.showInputDialog("Enter y-coordintes of the square  :"));
        int l = Integer.parseInt(JOptionPane.showInputDialog("Enter length :"));
        Rectangle rec=new Rectangle(p, l, l, Color.darkGray, Color.yellow);
        paintScreen1.addShape(rec);
        paintScreen1.repaint();
        paintScreen1.counter++;
        ChooseShape.addItem("Square " + paintScreen1.counter);
    }//GEN-LAST:event_squareButtonActionPerformed

    private void rectangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleButtonActionPerformed
        int x = Integer.parseInt(JOptionPane.showInputDialog("Enter x-coordintes of the rectangle  :"));
        int y = Integer.parseInt(JOptionPane.showInputDialog("Enter y-coordintes of the rectangle  :"));
        int l = Integer.parseInt(JOptionPane.showInputDialog("Enter length :"));
        int w = Integer.parseInt(JOptionPane.showInputDialog("Enter width :"));
        Point p=new Point(x, y);
        Rectangle rec=new Rectangle(p, l, w, Color.darkGray, Color.yellow);
        paintScreen1.addShape(rec);
        paintScreen1.repaint();
        paintScreen1.counter++;
        ChooseShape.addItem("Rectangle " + paintScreen1.counter);
    }//GEN-LAST:event_rectangleButtonActionPerformed

    private void linesegmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linesegmentButtonActionPerformed
        Point p =new Point();
        Point p1 =new Point();
        p.x=Integer.parseInt(JOptionPane.showInputDialog("Enter x-coordintes of the start point :"));
        p.y=Integer.parseInt(JOptionPane.showInputDialog("Enter y-coordintes of the start point :"));
        p1.x=Integer.parseInt(JOptionPane.showInputDialog("Enter x-coordintes of the end point :"));
        p1.y=Integer.parseInt(JOptionPane.showInputDialog("Enter y-coordintes of the end point :"));
        lineSegment ls=new lineSegment(p, p1, Color.darkGray);
        paintScreen1.addShape(ls);
        paintScreen1.repaint();
        paintScreen1.counter++;
        ChooseShape.addItem("LineSegment " + paintScreen1.counter);
        
    }//GEN-LAST:event_linesegmentButtonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        if (ChooseShape.getSelectedIndex()>0){
            paintScreen1.removeShape(paintScreen1.shapes.get(ChooseShape.getSelectedIndex() - 1));
            ChooseShape.removeItemAt(ChooseShape.getSelectedIndex());
            paintScreen1.counter--;
            int n=1;
            for(int i=1;i<=paintScreen1.counter;i++){
                String s[]=ChooseShape.getItemAt(n).split(" ");
                ChooseShape.addItem(s[0]+" "+i);
                ChooseShape.removeItemAt(n);
            }
            paintScreen1.removeAll();
            paintScreen1.repaint();
        }
        else
             JOptionPane.showMessageDialog(this,"Nothing to delete ","NO SHAPES",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void colorizebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorizebuttonActionPerformed
        if (ChooseShape.getSelectedIndex() > 0) {
            Color chosenBorderColor = JColorChooser.showDialog(null, "Select a border color", Color.white);
            Color chosenFillColor = JColorChooser.showDialog(null, "Select a filling color", Color.white);
            Shape temp = paintScreen1.shapes.get(ChooseShape.getSelectedIndex() - 1);
            temp.setFillColor(chosenFillColor);
            temp.setColor(chosenBorderColor);
            //paintScreen1.repaint();
        }
        else 
            JOptionPane.showMessageDialog(this,"Nothing to colorize ","NO SHAPES",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_colorizebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ChooseShape;
    private javax.swing.JLabel background;
    private javax.swing.JButton circleButton;
    private javax.swing.JLabel circlelabel;
    private javax.swing.JButton colorizebutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton linesegmentButton;
    private javax.swing.JLabel linesegmentlabel;
    private frontend.PaintScreen paintScreen1;
    private javax.swing.JButton rectangleButton;
    private javax.swing.JLabel rectanglelabel;
    private javax.swing.JLabel selectshapelabel;
    private javax.swing.JButton squareButton;
    private javax.swing.JLabel squarelabel;
    // End of variables declaration//GEN-END:variables
}
